/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playlist` | `/playlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-up)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-up)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(sign-in)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(sign-in)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/playlist` | `/playlist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(sign-up)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(sign-up)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(sign-in)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(sign-in)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/playlist${`?${string}` | `#${string}` | ''}` | `/playlist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(sign-up)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(sign-up)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playlist` | `/playlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-up)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-up)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
